name: clearcut_mobile
description: A native Android companion to https://clearcutradio.app/

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  audioplayers: ^6.1.0
  collection: ^1.17.0
  shared_preferences: ^2.0.15

  english_words: ^4.0.0
  provider: ^6.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
